/**
 * Compiled.ahk
 * 
 * This module is auto-generated by the BuildExe module. Shouldn't need to directly edit this file. 
 * The BuildExe.ahk module will auto-generate the lines between the RESOURCE BLOCK START and 
 * RESOURCE BLOCK END markers. Those lines are replaced each time BuildExe.ahk runs.
 * 
 * The code in this module is specific to and necessary for the compiled version of PACS Assistant.
 * 
 */



; ### RESOURCE BLOCK START ###

;@Ahk2Exe-SetProductVersion 0.7.0-beta
;@Ahk2Exe-SetCopyright Copyright 2025
;@Ahk2Exe-SetName PACS Assistant
;@Ahk2Exe-SetDescription PACS Assistant

;@Ahk2Exe-AddResource Lib\64bit\WebView2Loader.dll, 64bit\WebView2Loader.dll
;@Ahk2Exe-AddResource Lib\32bit\WebView2Loader.dll, 32bit\WebView2Loader.dll
;@Ahk2Exe-AddResource pages\PACSAssistant.html, pages\PACSAssistant.html
;@Ahk2Exe-AddResource pages\css\styles.css, pages\css\styles.css
;@Ahk2Exe-AddResource pages\images\EI-off.png, pages\images\EI-off.png
;@Ahk2Exe-AddResource pages\images\EI.png, pages\images\EI.png
;@Ahk2Exe-AddResource pages\images\EPIC-off.png, pages\images\EPIC-off.png
;@Ahk2Exe-AddResource pages\images\EPIC.png, pages\images\EPIC.png
;@Ahk2Exe-AddResource pages\images\help.png, pages\images\help.png
;@Ahk2Exe-AddResource pages\images\home.png, pages\images\home.png
;@Ahk2Exe-AddResource pages\images\info.png, pages\images\info.png
;@Ahk2Exe-AddResource pages\images\Network-connected.png, pages\images\Network-connected.png
;@Ahk2Exe-AddResource pages\images\Network-off.png, pages\images\Network-off.png
;@Ahk2Exe-AddResource pages\images\PA.png, pages\images\PA.png
;@Ahk2Exe-AddResource pages\images\power-green.png, pages\images\power-green.png
;@Ahk2Exe-AddResource pages\images\power-off.png, pages\images\power-off.png
;@Ahk2Exe-AddResource pages\images\power-yellow.png, pages\images\power-yellow.png
;@Ahk2Exe-AddResource pages\images\PS-off.png, pages\images\PS-off.png
;@Ahk2Exe-AddResource pages\images\PS.png, pages\images\PS.png
;@Ahk2Exe-AddResource pages\images\settings.png, pages\images\settings.png
;@Ahk2Exe-AddResource pages\images\VPN-connected.png, pages\images\VPN-connected.png
;@Ahk2Exe-AddResource pages\images\VPN-off.png, pages\images\VPN-off.png
;@Ahk2Exe-AddResource pages\images\VPN.png, pages\images\VPN.png
;@Ahk2Exe-AddResource pages\images\windows.png, pages\images\windows.png
;@Ahk2Exe-AddResource pages\js\scripts.js, pages\js\scripts.js

if (A_IsCompiled) {
	WebViewToo.CreateFileFromResource("64bit\WebView2Loader.dll")
	WebViewToo.CreateFileFromResource("32bit\WebView2Loader.dll")
	WebViewToo.CreateFileFromResource("pages\PACSAssistant.html")
	WebViewToo.CreateFileFromResource("pages\css\styles.css")
	WebViewToo.CreateFileFromResource("pages\images\EI-off.png")
	WebViewToo.CreateFileFromResource("pages\images\EI.png")
	WebViewToo.CreateFileFromResource("pages\images\EPIC-off.png")
	WebViewToo.CreateFileFromResource("pages\images\EPIC.png")
	WebViewToo.CreateFileFromResource("pages\images\help.png")
	WebViewToo.CreateFileFromResource("pages\images\home.png")
	WebViewToo.CreateFileFromResource("pages\images\info.png")
	WebViewToo.CreateFileFromResource("pages\images\Network-connected.png")
	WebViewToo.CreateFileFromResource("pages\images\Network-off.png")
	WebViewToo.CreateFileFromResource("pages\images\PA.png")
	WebViewToo.CreateFileFromResource("pages\images\power-green.png")
	WebViewToo.CreateFileFromResource("pages\images\power-off.png")
	WebViewToo.CreateFileFromResource("pages\images\power-yellow.png")
	WebViewToo.CreateFileFromResource("pages\images\PS-off.png")
	WebViewToo.CreateFileFromResource("pages\images\PS.png")
	WebViewToo.CreateFileFromResource("pages\images\settings.png")
	WebViewToo.CreateFileFromResource("pages\images\VPN-connected.png")
	WebViewToo.CreateFileFromResource("pages\images\VPN-off.png")
	WebViewToo.CreateFileFromResource("pages\images\VPN.png")
	WebViewToo.CreateFileFromResource("pages\images\windows.png")
	WebViewToo.CreateFileFromResource("pages\js\scripts.js")
}

FileInstall "PA.ico", "PA.ico", 1
FileInstall "icd10codes.txt", "icd10codes.txt", 1
FileInstall "README.md", "README.md", 1

; ### RESOURCE BLOCK END ###
